#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCT
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLCT")]
	public partial class QLCTDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKhoanChi(KhoanChi instance);
    partial void UpdateKhoanChi(KhoanChi instance);
    partial void DeleteKhoanChi(KhoanChi instance);
    partial void InsertKhoanNhan(KhoanNhan instance);
    partial void UpdateKhoanNhan(KhoanNhan instance);
    partial void DeleteKhoanNhan(KhoanNhan instance);
    #endregion
		
		public QLCTDataContext() : 
				base(global::QLCT.Properties.Settings.Default.QLCTConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLCTDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLCTDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLCTDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLCTDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<KhoanChi> KhoanChis
		{
			get
			{
				return this.GetTable<KhoanChi>();
			}
		}
		
		public System.Data.Linq.Table<KhoanNhan> KhoanNhans
		{
			get
			{
				return this.GetTable<KhoanNhan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhoanChi")]
	public partial class KhoanChi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SoThuTu;
		
		private string _TenKhoanChi;
		
		private string _LoaiKhoanChi;
		
		private System.DateTime _ThoiGian;
		
		private long _SoTien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSoThuTuChanging(int value);
    partial void OnSoThuTuChanged();
    partial void OnTenKhoanChiChanging(string value);
    partial void OnTenKhoanChiChanged();
    partial void OnLoaiKhoanChiChanging(string value);
    partial void OnLoaiKhoanChiChanged();
    partial void OnThoiGianChanging(System.DateTime value);
    partial void OnThoiGianChanged();
    partial void OnSoTienChanging(long value);
    partial void OnSoTienChanged();
    #endregion
		
		public KhoanChi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoThuTu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SoThuTu
		{
			get
			{
				return this._SoThuTu;
			}
			set
			{
				if ((this._SoThuTu != value))
				{
					this.OnSoThuTuChanging(value);
					this.SendPropertyChanging();
					this._SoThuTu = value;
					this.SendPropertyChanged("SoThuTu");
					this.OnSoThuTuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhoanChi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenKhoanChi
		{
			get
			{
				return this._TenKhoanChi;
			}
			set
			{
				if ((this._TenKhoanChi != value))
				{
					this.OnTenKhoanChiChanging(value);
					this.SendPropertyChanging();
					this._TenKhoanChi = value;
					this.SendPropertyChanged("TenKhoanChi");
					this.OnTenKhoanChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiKhoanChi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LoaiKhoanChi
		{
			get
			{
				return this._LoaiKhoanChi;
			}
			set
			{
				if ((this._LoaiKhoanChi != value))
				{
					this.OnLoaiKhoanChiChanging(value);
					this.SendPropertyChanging();
					this._LoaiKhoanChi = value;
					this.SendPropertyChanged("LoaiKhoanChi");
					this.OnLoaiKhoanChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGian", DbType="DateTime NOT NULL")]
		public System.DateTime ThoiGian
		{
			get
			{
				return this._ThoiGian;
			}
			set
			{
				if ((this._ThoiGian != value))
				{
					this.OnThoiGianChanging(value);
					this.SendPropertyChanging();
					this._ThoiGian = value;
					this.SendPropertyChanged("ThoiGian");
					this.OnThoiGianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTien", DbType="BigInt NOT NULL")]
		public long SoTien
		{
			get
			{
				return this._SoTien;
			}
			set
			{
				if ((this._SoTien != value))
				{
					this.OnSoTienChanging(value);
					this.SendPropertyChanging();
					this._SoTien = value;
					this.SendPropertyChanged("SoTien");
					this.OnSoTienChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhoanNhan")]
	public partial class KhoanNhan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SoThuTu;
		
		private string _TenKhoanNhan;
		
		private string _LoaiKhoanNhan;
		
		private System.DateTime _ThoiGian;
		
		private long _SoTien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSoThuTuChanging(int value);
    partial void OnSoThuTuChanged();
    partial void OnTenKhoanNhanChanging(string value);
    partial void OnTenKhoanNhanChanged();
    partial void OnLoaiKhoanNhanChanging(string value);
    partial void OnLoaiKhoanNhanChanged();
    partial void OnThoiGianChanging(System.DateTime value);
    partial void OnThoiGianChanged();
    partial void OnSoTienChanging(long value);
    partial void OnSoTienChanged();
    #endregion
		
		public KhoanNhan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoThuTu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SoThuTu
		{
			get
			{
				return this._SoThuTu;
			}
			set
			{
				if ((this._SoThuTu != value))
				{
					this.OnSoThuTuChanging(value);
					this.SendPropertyChanging();
					this._SoThuTu = value;
					this.SendPropertyChanged("SoThuTu");
					this.OnSoThuTuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhoanNhan", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenKhoanNhan
		{
			get
			{
				return this._TenKhoanNhan;
			}
			set
			{
				if ((this._TenKhoanNhan != value))
				{
					this.OnTenKhoanNhanChanging(value);
					this.SendPropertyChanging();
					this._TenKhoanNhan = value;
					this.SendPropertyChanged("TenKhoanNhan");
					this.OnTenKhoanNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiKhoanNhan", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LoaiKhoanNhan
		{
			get
			{
				return this._LoaiKhoanNhan;
			}
			set
			{
				if ((this._LoaiKhoanNhan != value))
				{
					this.OnLoaiKhoanNhanChanging(value);
					this.SendPropertyChanging();
					this._LoaiKhoanNhan = value;
					this.SendPropertyChanged("LoaiKhoanNhan");
					this.OnLoaiKhoanNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGian", DbType="DateTime NOT NULL")]
		public System.DateTime ThoiGian
		{
			get
			{
				return this._ThoiGian;
			}
			set
			{
				if ((this._ThoiGian != value))
				{
					this.OnThoiGianChanging(value);
					this.SendPropertyChanging();
					this._ThoiGian = value;
					this.SendPropertyChanged("ThoiGian");
					this.OnThoiGianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTien", DbType="BigInt NOT NULL")]
		public long SoTien
		{
			get
			{
				return this._SoTien;
			}
			set
			{
				if ((this._SoTien != value))
				{
					this.OnSoTienChanging(value);
					this.SendPropertyChanging();
					this._SoTien = value;
					this.SendPropertyChanged("SoTien");
					this.OnSoTienChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
